### ISSUE TITLE
Possible to use with gatsby-remark-images?

### ISSUE THREAD

**Issue by krismorf** [humanseelabs/gatsby-plugin-lunr#8]
Is it possible to use with gatsby-remark-images?

**Comment by deemaagog** [comment]
I see no problem, could you elaborate?

**Comment by krismorf** [comment]
I can query my images using this: `image: node => node.frontmatter.image`
This returns a path to my image as it is read from the markdown files i.e `image: "/img/image.jpg"`.

But I need to query the following
`image: node => node.frontmatter.image.childImageSharp.fluid`
so that my store has the following:
```
image:
    childImageSharp:
        fluid:
            aspectRatio:
            base64:
            sizes:
            src:
            srcSet:
            srcSetWebp:
            srcWebp:
```
